# Generated by Django 5.1.5 on 2025-01-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowbook",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowed_books",
                to="user.user",
            ),
        ),
        migrations.AddField(
            model_name="fine",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="book.book"
            ),
        ),
        migrations.AddField(
            model_name="fine",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fines",
                to="user.user",
            ),
        ),
    ]
