# Generated by Django 5.1.5 on 2025-01-30 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_alter_borrowbook_return_deadline"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fine",
        ),
    ]
